---
# Installing and configuring mysql
- name: Installing Mysql-server package
  yum:
    name: [mysql-server, MySQL-python27]
    state: present

- name: Restarting the services
  service: name=mysqld state=started enabled=yes

- name: Create a new database with name 'wiki_db'
  mysql_db: name={{mysql_db_name}} state=present

- name: Resetting the root password of mysql
  mysql_user: name={{mysql_user}} host={{item}} password={{mysql_password}} priv=*.*:ALL,GRANT state=present
  with_items:
    - "{{groups['role_app']}}"

- name: Set mysql user privileges
  mysql_user: name={{mysql_user}} priv=*.*:ALL,GRANT state=present
